[2022-12-17T14:55:10.412+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:55:07.337042+00:00 [queued]>
[2022-12-17T14:55:10.421+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:55:07.337042+00:00 [queued]>
[2022-12-17T14:55:10.421+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:55:10.421+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-17T14:55:10.421+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:55:10.435+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 14:55:07.337042+00:00
[2022-12-17T14:55:10.440+0000] {standard_task_runner.py:55} INFO - Started process 27055 to run task
[2022-12-17T14:55:10.443+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T14:55:07.337042+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmpis9dqxf8']
[2022-12-17T14:55:10.445+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask proceso
[2022-12-17T14:55:10.508+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:55:07.337042+00:00 [running]> on host 26302dc28230
[2022-12-17T14:55:10.740+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T14:55:07.337042+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T14:55:07.337042+00:00
[2022-12-17T14:55:11.272+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T14:55:11.291+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpgc09bzw2/5shopx64.json
[2022-12-17T14:55:11.296+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpgc09bzw2/w4a95j9b.json
[2022-12-17T14:55:11.296+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T14:55:11.296+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T14:55:11.297+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61422', 'data', 'file=/tmp/tmpgc09bzw2/5shopx64.json', 'init=/tmp/tmpgc09bzw2/w4a95j9b.json', 'output', 'file=/tmp/tmpgc09bzw2/prophet_model23exukau/prophet_model-20221217145511.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T14:55:11.297+0000] {logging_mixin.py:120} WARNING - 14:55:11 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T14:55:11.297+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T14:55:11.855+0000] {logging_mixin.py:120} WARNING - 14:55:11 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T14:55:11.854+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T14:55:12.275+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 32, in proceso
    Outp.to_csv(outputpath)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/dags/historico.csv'
[2022-12-17T14:55:12.286+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T145507, start_date=20221217T145510, end_date=20221217T145512
[2022-12-17T14:55:12.299+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 102 for task proceso ([Errno 2] No such file or directory: '/dags/historico.csv'; 27055)
[2022-12-17T14:55:12.344+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T14:55:12.363+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
