[2022-12-17T14:30:33.612+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:30:29.623075+00:00 [queued]>
[2022-12-17T14:30:33.621+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:30:29.623075+00:00 [queued]>
[2022-12-17T14:30:33.621+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:30:33.621+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-17T14:30:33.621+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:30:33.635+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 14:30:29.623075+00:00
[2022-12-17T14:30:33.640+0000] {standard_task_runner.py:55} INFO - Started process 25477 to run task
[2022-12-17T14:30:33.643+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T14:30:29.623075+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmpuzvoo6wv']
[2022-12-17T14:30:33.644+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask proceso
[2022-12-17T14:30:33.712+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:30:29.623075+00:00 [running]> on host 26302dc28230
[2022-12-17T14:30:33.941+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T14:30:29.623075+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T14:30:29.623075+00:00
[2022-12-17T14:30:35.721+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T14:30:35.741+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmp6adkv0xq/clkj62_l.json
[2022-12-17T14:30:35.747+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmp6adkv0xq/ke90sfiq.json
[2022-12-17T14:30:35.748+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T14:30:35.748+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T14:30:35.748+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86999', 'data', 'file=/tmp/tmp6adkv0xq/clkj62_l.json', 'init=/tmp/tmp6adkv0xq/ke90sfiq.json', 'output', 'file=/tmp/tmp6adkv0xq/prophet_model3ow7yf00/prophet_model-20221217143035.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T14:30:35.748+0000] {logging_mixin.py:120} WARNING - 14:30:35 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T14:30:35.748+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T14:30:36.329+0000] {logging_mixin.py:120} WARNING - 14:30:36 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T14:30:36.329+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T14:30:36.745+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 33, in proceso
    os.mkdir('/outputs')
PermissionError: [Errno 13] Permission denied: '/outputs'
[2022-12-17T14:30:36.753+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T143029, start_date=20221217T143033, end_date=20221217T143036
[2022-12-17T14:30:36.779+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 95 for task proceso ([Errno 13] Permission denied: '/outputs'; 25477)
[2022-12-17T14:30:36.832+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T14:30:36.880+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
