[2022-12-17T14:32:39.840+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:30:29.623075+00:00 [queued]>
[2022-12-17T14:32:39.849+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:30:29.623075+00:00 [queued]>
[2022-12-17T14:32:39.849+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:32:39.850+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-17T14:32:39.850+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:32:39.865+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 14:30:29.623075+00:00
[2022-12-17T14:32:39.870+0000] {standard_task_runner.py:55} INFO - Started process 25614 to run task
[2022-12-17T14:32:39.873+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T14:30:29.623075+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmpaqp4idvv']
[2022-12-17T14:32:39.875+0000] {standard_task_runner.py:83} INFO - Job 96: Subtask proceso
[2022-12-17T14:32:39.939+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:30:29.623075+00:00 [running]> on host 26302dc28230
[2022-12-17T14:32:40.176+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T14:30:29.623075+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T14:30:29.623075+00:00
[2022-12-17T14:32:40.617+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T14:32:40.647+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpampoli6x/sxdd4w4o.json
[2022-12-17T14:32:40.653+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpampoli6x/6na_4vg1.json
[2022-12-17T14:32:40.655+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T14:32:40.655+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T14:32:40.655+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28086', 'data', 'file=/tmp/tmpampoli6x/sxdd4w4o.json', 'init=/tmp/tmpampoli6x/6na_4vg1.json', 'output', 'file=/tmp/tmpampoli6x/prophet_modeleetbimcx/prophet_model-20221217143240.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T14:32:40.655+0000] {logging_mixin.py:120} WARNING - 14:32:40 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T14:32:40.655+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T14:32:41.376+0000] {logging_mixin.py:120} WARNING - 14:32:41 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T14:32:41.375+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T14:32:41.843+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 33, in proceso
    os.mkdir('/outputs')
PermissionError: [Errno 13] Permission denied: '/outputs'
[2022-12-17T14:32:41.852+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T143029, start_date=20221217T143239, end_date=20221217T143241
[2022-12-17T14:32:41.876+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 96 for task proceso ([Errno 13] Permission denied: '/outputs'; 25614)
[2022-12-17T14:32:41.894+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T14:32:41.914+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
