[2022-12-17T14:42:01.145+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:41:58.325826+00:00 [queued]>
[2022-12-17T14:42:01.154+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:41:58.325826+00:00 [queued]>
[2022-12-17T14:42:01.154+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:42:01.154+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-17T14:42:01.154+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:42:01.169+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 14:41:58.325826+00:00
[2022-12-17T14:42:01.174+0000] {standard_task_runner.py:55} INFO - Started process 26209 to run task
[2022-12-17T14:42:01.177+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T14:41:58.325826+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmpw60g5x9s']
[2022-12-17T14:42:01.178+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask proceso
[2022-12-17T14:42:01.239+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:41:58.325826+00:00 [running]> on host 26302dc28230
[2022-12-17T14:42:01.478+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T14:41:58.325826+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T14:41:58.325826+00:00
[2022-12-17T14:42:01.938+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T14:42:01.954+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpdiy1fonk/dhtcuk2g.json
[2022-12-17T14:42:01.959+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpdiy1fonk/g5gt8v0v.json
[2022-12-17T14:42:01.960+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T14:42:01.961+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T14:42:01.961+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6995', 'data', 'file=/tmp/tmpdiy1fonk/dhtcuk2g.json', 'init=/tmp/tmpdiy1fonk/g5gt8v0v.json', 'output', 'file=/tmp/tmpdiy1fonk/prophet_modeld6okdp8x/prophet_model-20221217144201.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T14:42:01.961+0000] {logging_mixin.py:120} WARNING - 14:42:01 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T14:42:01.961+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T14:42:02.517+0000] {logging_mixin.py:120} WARNING - 14:42:02 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T14:42:02.516+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T14:42:02.939+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 34, in proceso
    fcst[['ds', 'yhat']].merge(df,on='ds',how='left').to_csv('/dags/historico.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/dags/historico.csv'
[2022-12-17T14:42:02.948+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T144158, start_date=20221217T144201, end_date=20221217T144202
[2022-12-17T14:42:02.960+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 98 for task proceso ([Errno 2] No such file or directory: '/dags/historico.csv'; 26209)
[2022-12-17T14:42:02.997+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T14:42:03.016+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
