[2022-12-17T13:28:38.280+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T13:26:28.247017+00:00 [queued]>
[2022-12-17T13:28:38.288+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T13:26:28.247017+00:00 [queued]>
[2022-12-17T13:28:38.289+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T13:28:38.289+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-17T13:28:38.289+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T13:28:38.302+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 13:26:28.247017+00:00
[2022-12-17T13:28:38.308+0000] {standard_task_runner.py:55} INFO - Started process 21546 to run task
[2022-12-17T13:28:38.312+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T13:26:28.247017+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmptsf0ovgy']
[2022-12-17T13:28:38.314+0000] {standard_task_runner.py:83} INFO - Job 83: Subtask proceso
[2022-12-17T13:28:38.427+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T13:26:28.247017+00:00 [running]> on host 26302dc28230
[2022-12-17T13:28:38.684+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T13:26:28.247017+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T13:26:28.247017+00:00
[2022-12-17T13:28:39.093+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T13:28:39.110+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpvtop1p1s/8qh9qmg_.json
[2022-12-17T13:28:39.115+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpvtop1p1s/4466k8a6.json
[2022-12-17T13:28:39.116+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T13:28:39.116+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T13:28:39.117+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31328', 'data', 'file=/tmp/tmpvtop1p1s/8qh9qmg_.json', 'init=/tmp/tmpvtop1p1s/4466k8a6.json', 'output', 'file=/tmp/tmpvtop1p1s/prophet_modelr25vq8sv/prophet_model-20221217132839.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T13:28:39.117+0000] {logging_mixin.py:120} WARNING - 13:28:39 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T13:28:39.117+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T13:28:39.760+0000] {logging_mixin.py:120} WARNING - 13:28:39 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T13:28:39.759+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T13:28:40.245+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 29, in proceso
    print(os.getcwd())
NameError: name 'os' is not defined
[2022-12-17T13:28:40.254+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T132628, start_date=20221217T132838, end_date=20221217T132840
[2022-12-17T13:28:40.271+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 83 for task proceso (name 'os' is not defined; 21546)
[2022-12-17T13:28:40.291+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T13:28:40.309+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
